version: "3.2"
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: "rabbitmq"
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - rabbitmq
    restart: unless-stopped

  redis:
    image: redis:latest
    volumes:
      - ./redis.conf:/redis.conf:ro
    container_name: redis_api
    ports:
      - "6379:6379"
    command: ["redis-server", "/redis.conf"]

networks:
  rabbitmq:
    driver: bridge
